const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const buildInputsHash = require("./buildInputsHash.util");

const { cargoManifestsFor } = buildInputsHash;

const SOURCE = "#[no_mangle]\npub fn fib(n: u32) -> u32 { n }\n";

const MANIFEST = [
    "[package]",
    'name = "probe"',
    'version = "0.1.0"',
    "",
    "[lib]",
    'crate-type = ["cdylib"]',
    'path = "math.rs"',
    "",
    "[dependencies]",
    'wasm-bindgen = "0.2.95"',
    "",
].join("\n");

const lockWith = (version) =>
    [
        "# This file is automatically @generated by Cargo.",
        "version = 4",
        "",
        "[[package]]",
        'name = "wasm-bindgen"',
        `version = "${version}"`,
        "",
    ].join("\n");

// A throwaway crate on disk. The hash reads the manifest pair off the file
// system, so the fixtures are files rather than strings.
function crate({ manifest = MANIFEST, lock = lockWith("0.2.95") } = {}) {
    const dir = fs.realpathSync(
        fs.mkdtempSync(path.join(os.tmpdir(), "rs-inputs-")),
    );
    fs.writeFileSync(path.join(dir, "math.rs"), SOURCE);
    fs.writeFileSync(path.join(dir, "Cargo.toml"), manifest);
    if (lock !== null) {
        fs.writeFileSync(path.join(dir, "Cargo.lock"), lock);
    }
    return dir;
}

const hashOf = (dir, source = SOURCE) =>
    buildInputsHash(source, path.join(dir, "math.rs"), dir);

const cleanup = (dirs) =>
    dirs.forEach((dir) => fs.rmSync(dir, { recursive: true, force: true }));

test("gives one digest to one set of inputs", () => {
    const dirs = [crate(), crate()];
    try {
        assert.equal(hashOf(dirs[0]), hashOf(dirs[1]));
    } finally {
        cleanup(dirs);
    }
});

test("changes the digest when the lock resolves another version", () => {
    const dirs = [crate(), crate({ lock: lockWith("0.2.128") })];
    try {
        assert.notEqual(hashOf(dirs[0]), hashOf(dirs[1]));
    } finally {
        cleanup(dirs);
    }
});

test("changes the digest when the manifest changes without the lock", () => {
    const dirs = [
        crate(),
        crate({
            manifest: `${MANIFEST}\n[profile.release]\nopt-level = "z"\n`,
        }),
    ];
    try {
        assert.notEqual(hashOf(dirs[0]), hashOf(dirs[1]));
    } finally {
        cleanup(dirs);
    }
});

test("changes the digest when the source changes", () => {
    const dir = crate();
    try {
        assert.notEqual(hashOf(dir), hashOf(dir, `${SOURCE}// edit\n`));
    } finally {
        cleanup([dir]);
    }
});

test("gives a lockless crate a stable digest of its own", () => {
    const dirs = [crate({ lock: null }), crate({ lock: null }), crate()];
    try {
        assert.equal(hashOf(dirs[0]), hashOf(dirs[1]));
        assert.notEqual(hashOf(dirs[0]), hashOf(dirs[2]));
    } finally {
        cleanup(dirs);
    }
});

// A crate whose entry sits one folder below the manifest that owns it.
function nestedCrate(lock) {
    const dir = crate({
        manifest: MANIFEST.replace(
            'path = "math.rs"',
            'path = "nested/math.rs"',
        ),
        lock,
    });
    fs.mkdirSync(path.join(dir, "nested"));
    fs.writeFileSync(path.join(dir, "nested", "math.rs"), SOURCE);
    return dir;
}

test("reads the manifest pair of the crate that owns a nested entry", () => {
    const dirs = [
        nestedCrate(lockWith("0.2.95")),
        nestedCrate(lockWith("0.2.128")),
    ];
    try {
        const digests = dirs.map((dir) =>
            buildInputsHash(SOURCE, path.join(dir, "nested", "math.rs"), dir),
        );
        assert.notEqual(digests[0], digests[1]);
    } finally {
        cleanup(dirs);
    }
});

test("throws when no manifest owns the entry", () => {
    const dir = fs.realpathSync(
        fs.mkdtempSync(path.join(os.tmpdir(), "rs-inputs-bare-")),
    );
    try {
        fs.writeFileSync(path.join(dir, "math.rs"), SOURCE);
        assert.throws(() => hashOf(dir), {
            message: /Cannot Find "Cargo\.toml" to create wasm/,
        });
    } finally {
        cleanup([dir]);
    }
});

test("lists the manifests the digest reads, so a loader can declare them", () => {
    const dir = crate();
    try {
        assert.deepEqual(cargoManifestsFor(path.join(dir, "math.rs"), dir), [
            path.join(dir, "Cargo.toml"),
            path.join(dir, "Cargo.lock"),
        ]);
    } finally {
        cleanup([dir]);
    }
});

test("leaves out a lock that does not exist", () => {
    const dir = crate({ lock: null });
    try {
        assert.deepEqual(cargoManifestsFor(path.join(dir, "math.rs"), dir), [
            path.join(dir, "Cargo.toml"),
        ]);
    } finally {
        cleanup([dir]);
    }
});
