name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
        paths:
            - 'docs/**'
            - 'README.md'
            - 'CHANGELOG.md'
            - 'CONTRIBUTING.md'
            - 'package.json'
            - '.github/workflows/docs.yml'
    workflow_dispatch:

jobs:
    build:
        name: Build Docusaurus
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
                with:
                    fetch-depth: 0
            -   uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
                with:
                    node-version: 22
                    cache: npm

            -   name: Install dependencies
                run: |
                    npm ci --ignore-scripts
                    npm install @docusaurus/core@3.10.1 @docusaurus/module-type-aliases@3.10.1 @docusaurus/preset-classic@3.10.1 @docusaurus/tsconfig@3.10.1 @docusaurus/types@3.10.1 @docusaurus/theme-mermaid@3.10.1 @mermaid-js/layout-elk@0.1.9 --ignore-scripts
            
            -   name: Build website
                run: npm run docs:build

            -   name: Upload Build Artifact
                uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
                with:
                    path: build
    
    deploy:
        name: Deploy to GitHub Pages
        needs: build

        permissions:
            pages: write
            id-token: write
        
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1