name: Test Docs Deployment

on:
    pull_request:
        branches:
            - main
        paths:
            - 'docs/**'
            - 'README.md'
            - 'CHANGELOG.md'
            - 'CONTRIBUTING.md'
            - 'package.json'
            - '.github/workflows/docs.yml'
            - '.github/workflows/docs-test.yaml'

jobs:
    test-deploy:
        name: Test deployment
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   uses: actions/setup-node@v4
                with:
                    node-version: 20
                    cache: npm

            -   name: Install dependencies
                run: |
                    npm ci
                    npm install @docusaurus/core @docusaurus/module-type-aliases @docusaurus/preset-classic @docusaurus/tsconfig @docusaurus/types @docusaurus/theme-mermaid
            
            -   name: Test build website
                run: npm run docs:build