name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main
        paths:
            - 'docs/**'
            - 'README.md'
            - 'CHANGELOG.md'
            - 'CONTRIBUTING.md'
            - 'package.json'
            - '.github/workflows/docs.yml'
    workflow_dispatch:

jobs:
    build:
        name: Build Docusaurus
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   uses: actions/setup-node@v4
                with:
                    node-version: 20
                    cache: npm

            -   name: Install dependencies
                run: |
                    npm ci
                    npm install @docusaurus/core @docusaurus/module-type-aliases @docusaurus/preset-classic @docusaurus/tsconfig @docusaurus/types @docusaurus/theme-mermaid
            
            -   name: Build website
                run: npm run docs:build

            -   name: Upload Build Artifact
                uses: actions/upload-pages-artifact@v3
                with:
                    path: build
    
    deploy:
        name: Deploy to GitHub Pages
        needs: build

        permissions:
            pages: write
            id-token: write
        
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        
        runs-on: ubuntu-latest
        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4